#!/bin/bash
if [[ $(whoami) != "root" ]];then
	echo -e "\033[1;31m[-]\033[0m You aren't root"
	exit
fi

function operation(){
	function loading(){
		while [ true ]
		do
			echo -ne "."
			sleep 2
		done
	}
	echo -ne $1
	loading&
	PID_loading=$!
	# if the installation or uninstallation have dialogs, it doesn't show it, but is executed.
	if [[ $3 = 1 ]];then
		$2
		echo -ne "\033[1;32mOK\033[0m"
	else
		DEBIAN_FRONTEND=nointeractive $2 > /dev/null 2>&1
		echo -ne "\033[1;32mOK\033[0m"
	fi
	kill -19 $PID_loading > /dev/null 2>&1
	echo ""
}
echo -ne "Uninstall dialog? [Y/n] "
read ask_dialog
	if [[ $ask_dialog == "Y" ]] || [[ $ask_dialog == "y" ]];then
		operation "uninstalling dialog" "apt-get purge -y dialog"
	fi

declare -r LIST_SERVICES="/var/cache/notifybox/services.list"
while IFS= read -r line
do
	path=$(find /lib/systemd/ -type f -iname "$line")
        if [[ $path != "" ]];then
                if [[ $(cat $path | grep -E -o "notifybox --") ]];then
			number_options=$(cat $path | grep "notifybox" | wc -l)
			for i in $(1 $number_options)
			do
				number=$(cat -n $path | grep "notifybox" | grep -E -o "[0-9]+" | head -n 1 )
				sed -i "${number}d" $path
			done
		fi
        fi
done < $LIST_SERVICES
operation "restarting daemons" "systemctl daemon-reload"
operation "deleting directory /etc/notifybox/" "rm -rf /etc/notifybox"
operation "deleting derectory /var/cache/notifybox/" "rm -rf /var/cache/notifybox/"
operation "deleting dialog permissions" "chmod o-w /etc/dialogrc"
operation "deleting command" "rm -rf /bin/notifybox"
operation "deleting notifybox-conf" "rm -rf /bin/notifybox-conf"
echo -e "\033[1;32m ^|^t\033[0m Uninstallation completed"
rm -rf "/bin/notifybox-uninstaller"
