#!/bin/bash
if [[ $(whoami) != "root" ]];then
	echo -e "\033[1;31m[-]\033[0m You aren't root"
	exit
fi
function operation(){
	function loading(){
		while [ true ]
		do
			echo -ne "."
			sleep 2
		done
	}
	echo -ne $1
	loading&
	PID_loading=$!
	# if the installation or uninstallation have dialogs, it doesn't show it, but is executed.
	if [[ $3 = 1 ]];then
		$2
		echo -ne "\033[1;32mOK\033[0m"
	else
		DEBIAN_FRONTEND=nointeractive $2 > /dev/null 2>&1
		echo -ne "\033[1;32mOK\033[0m"
	fi
	kill -19 $PID_loading > /dev/null 2>&1
	echo ""
}
echo -ne "Uninstall dialog? [Y/n] "
read ask_dialog
	if [[ $ask_dialog == "Y" ]] || [[ $ask_dialog == "y" ]];then
		operation "uninstalling dialog" "apt-get purge -y dialog"
	fi
operation "deleting directory" "rm -rf /etc/notifybox"
operation "deleting dialog permissions" "chmod o-w /etc/dialogrc"
operation "deleting command" "shred -u /bin/notifybox"
operation "deleting uninstaller" "shred -u /bin/notifybox-uninstaller"
echo -e "\033[1;34m[i]\033[0m uninstallation completed"
